# Generated by Django 5.1.1 on 2024-09-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizador",
            name="telefono",
        ),
        migrations.AddField(
            model_name="evento",
            name="ubicacion",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to="eventos.organizador",
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
